---
title: "EDS 221 Interactive Session"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here) 
library(janitor)

library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)

library(gapminder)

library(sf)
```

```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))

```

```{r}
ggplot(data = lizards, aes(x = total_length,
                           y = weight)) +
  geom_point()

ggplot(data = lizards) +
  geom_point(aes(x = total_length,
                 y = weight))

ggplot() +
  geom_point(data = lizards, aes(x = total_length, 
                                 y = weight))
```

```{r}
ggplot(lizards, aes(x = total_length)) +
  geom_histogram()
```

```{r}
ggplot(lizards, aes(y = common_name, x = weight)) +
  geom_jitter() +theme_classic()
```

```{r}
ggplot(data = lizards, aes(x = weight)) +
  geom_histogram(color = "blue",
                 fill = "lavender",
                 linewidth = 2,
                 linetype = "dotted")
```

```{r}
ggplot(data = lizards, aes(x = total_length, y= weight)) +
  geom_point(color = "coral3",
             shape = 22, 
             size = 3,
             alpha = 0.2)
```

```{r}

ggplot(data = lizards, aes(x = total_length, y= weight)) +
  geom_point(aes(color = common_name, 
                 size = total_length), alpha= 0.5) +
  scale_color_discrete() +
  scale_color_brewer("palette" = "Set3")
```

```{r}
ggplot(data = lizards, aes(x = site, y = weight)) +
  geom_jitter(aes(color = common_name)) +
  theme_light()
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  labs(x = "Total Length (mm)", 
       y = "Weight (grams)",
       title = "Lizard size") 
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  facet_wrap(~common_name, ncol = 3, scales = "free") +
  labs(x = "Total length (mm)",
       y= "Weight (grams)")
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  facet_grid(sex~tail)
```

```{r}
lizards_counts <- lizards |> 
  count(common_name)

ggplot(lizards_counts, aes(y = fct_reorder(common_name, n), x = n)) +
  geom_col()


```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name), 
             size = 2) +
  theme_minimal() +
  labs(x = "Total length (mm)", 
       y = "Weight (g)",
       color = "Lizard Species") +
  facet_wrap(~common_name, scales = "free")
```

```{r}
ggplot(lizards, aes(y = fct_infreq(common_name))) +
  geom_bar(aes(fill = site)) +
  theme_minimal() +
  labs(x = "Lizard counts",
       y = "Species (common names)") +
  facet_grid(sex~tail)
```

```{r}
ggplot(lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  scale_x_continuous(breaks = c(0, 250, 500), 
                     limits = c(0, 500)) +
  scale_y_continuous(breaks = seq(from = 0, to = 70, by = 10),
                     limits = c(0, 70)) +
  theme_light()
```

```{r}
lizard_counts <- lizards |>  mutate(date = lubridate::mdy(date)) |> 
  count(date)

ggplot(lizard_counts, aes(x = date, y = n)) + 
  geom_line() +
  scale_x_date(breaks = scales::breaks_width("3 years"),
               labels = scales::label_date("'%y"))
```

```{r}
ggplot(lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = weight)) +
  scale_color_steps(low = "red", high = "black")
  #scale_color_gradient(colors = c("orange", "red", "purple", "navy", "black"))
```

```{r}
p <- ggplot(data = lizards, aes(x = total_length, y= weight)) +
  geom_point()

p + theme(panel.grid.minor = element_blank(),
          panel.grid.major = element_line(color = "red"),
plot.background = element_rect(fill = "pink"),
text = element_text(size = 12, family = "wingdings"),
axis.text.y = element_text(color = "blue")) +
  geom_hline(yintercept= mean(lizards$weight), color = "blue", linetype = "dashed") +
  annotate("text", x = 350, y = mean(lizards$weight) + 2, label = "Mean weight")
```

```{r}
mono <- read_csv(here("data_tidy", "mono.csv")) 
```

```{r}
ggplot(data = mono, aes(x = year, y = lake_level)) +
  geom_rect(aes(xmin = 1941, 
                xmax = 1983, 
                ymin = 6350, 
                ymax = 6440), 
            fill = "gray90") +
  geom_line() +
  labs(x = "\nYear",
       y = "Lake surface level\n(feet above sea level)\n",
       title = "Mono Lake levels (1850 - 2017)\n",
       caption = "Data: Mono Basin Clearinghouse") +
  scale_x_continuous(limits = c(1850, 2020), 
                     expand = c(0,0),
                     breaks = seq(1850, 2010, by = 20)) +
  scale_y_continuous(limits = c(6350, 6440), 
                     breaks = c(6370, 6400, 6430),
                     expand = c(0,0), 
                     labels = scales::label_comma()) +
  annotate("text", x = 1962, y = 6425, 
           label = "unrestricted diversions\n(1941 - 1983)",
           size = 3) +
  theme_minimal() +
  theme(plot.title.position = "plot",
        axis.text.y = element_text(face = "italic")) +
  geom_hline(yintercept = 6360, linetype = "dashed") +
  annotate("text", 
           x = 1910, 
           y = 6367, 
           label = "Decreased shrimp abundance expected\n(6,360 feet above sea level)",
           size = 3)
```
